/**
 * Единый источник списка брендов (витрина + страница /brands).
 *
 * ⚠️ Долг: productCount — выдуманные числа, не из БД. Не тиражировать на новые
 * поверхности как факт. На главной показываем только логотипы (logo wall),
 * без чисел. Когда появится реальный count по manufacturerId — заменить.
 */

export interface Brand {
  id: string
  name: string
  country: string
  flag: string
  logo: string | null
  categories: string[]
  productCount: number
  featured: boolean
  /** размер карточки в топ-мозаике: 'large' | 'medium' | 'small' */
  size?: 'large' | 'medium' | 'small'
}

export const BRANDS: Brand[] = [
  // ── Китай ──────────────────────────────────────────────
  {
    id: 'espressif',
    name: 'Espressif',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/espressi.png',
    categories: ['Контроллеры', 'WiFi-модули', 'Bluetooth'],
    productCount: 4200,
    featured: true,
    size: 'large',
  },
  {
    id: 'worldsemi',
    name: 'WorldSemi',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/worldsemi.png',
    categories: ['Светодиоды', 'RGB', 'LED-матрицы'],
    productCount: 28000,
    featured: true,
    size: 'medium',
  },
  {
    id: 'wch',
    name: 'WCH',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/wch.png',
    categories: ['USB-мосты', 'Микроконтроллеры', 'RISC-V'],
    productCount: 1800,
    featured: true,
    size: 'medium',
  },
  {
    id: 'hilink',
    name: 'Hi-Link',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/hilink.png',
    categories: ['Блоки питания', 'AC-DC', 'Модули'],
    productCount: 3400,
    featured: true,
    size: 'medium',
  },
  {
    id: 'gigadevice',
    name: 'GigaDevice',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/gigadevice.png',
    categories: ['Flash-память', 'Микроконтроллеры'],
    productCount: 6100,
    featured: true,
    size: 'medium',
  },
  {
    id: 'winbond',
    name: 'Winbond',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/winbond.png',
    categories: ['Flash-память', 'DRAM'],
    productCount: 9200,
    featured: true,
    size: 'small',
  },
  {
    id: 'holtek',
    name: 'Holtek',
    country: 'Китай',
    flag: '🇨🇳',
    logo: '/brands/holtek.png',
    categories: ['Микроконтроллеры', 'Микросхемы'],
    productCount: 5600,
    featured: false,
    size: 'small',
  },
  {
    id: 'songle',
    name: 'Songle',
    country: 'Китай',
    flag: '🇨🇳',
    logo: null,
    categories: ['Реле', 'Автоматика'],
    productCount: 4200,
    featured: false,
    size: 'small',
  },
  // ── Тайвань / Япония / Европа / США ───────────────────
  {
    id: 'yageo',
    name: 'Yageo',
    country: 'Тайвань',
    flag: '🇹🇼',
    logo: '/brands/yageo.png',
    categories: ['Резисторы', 'Конденсаторы', 'Индуктивности'],
    productCount: 48200,
    featured: true,
    size: 'large',
  },
  {
    id: 'murata',
    name: 'Murata',
    country: 'Япония',
    flag: '🇯🇵',
    logo: '/brands/murata.png',
    categories: ['Конденсаторы', 'Фильтры', 'Модули'],
    productCount: 31500,
    featured: true,
    size: 'medium',
  },
  {
    id: 'stmicroelectronics',
    name: 'STMicroelectronics',
    country: 'Швейцария',
    flag: '🇨🇭',
    logo: '/brands/stmicroelectronics.svg',
    categories: ['Микроконтроллеры', 'Силовые устройства', 'Датчики'],
    productCount: 12400,
    featured: true,
    size: 'medium',
  },
  {
    id: 'infineon',
    name: 'Infineon',
    country: 'Германия',
    flag: '🇩🇪',
    logo: '/brands/infineon.png',
    categories: ['Транзисторы', 'Диоды', 'Микросхемы'],
    productCount: 18700,
    featured: true,
    size: 'medium',
  },
  {
    id: 'texas-instruments',
    name: 'Texas Instruments',
    country: 'США',
    flag: '🇺🇸',
    logo: '/brands/texas-instruments.png',
    categories: ['Микросхемы', 'АЦП/ЦАП', 'Усилители'],
    productCount: 24600,
    featured: true,
    size: 'medium',
  },
  {
    id: 'vishay',
    name: 'Vishay',
    country: 'США',
    flag: '🇺🇸',
    logo: '/brands/vishay.png',
    categories: ['Диоды', 'Резисторы', 'Конденсаторы'],
    productCount: 45000,
    featured: false,
    size: 'small',
  },
  {
    id: 'analog-devices',
    name: 'Analog Devices',
    country: 'США',
    flag: '🇺🇸',
    logo: '/brands/analog-devices.png',
    categories: ['Датчики', 'АЦП/ЦАП', 'Усилители'],
    productCount: 6700,
    featured: false,
    size: 'small',
  },
  {
    id: 'xilinx',
    name: 'Xilinx',
    country: 'США',
    flag: '🇺🇸',
    logo: '/brands/Xilinx-Logo.png',
    categories: ['FPGA', 'Программируемая логика', 'SoC'],
    productCount: 3200,
    featured: true,
    size: 'medium',
  },
  {
    id: 'sharp',
    name: 'Sharp',
    country: 'Япония',
    flag: '🇯🇵',
    logo: '/brands/Sharp.png',
    categories: ['Оптопары', 'Фотодиоды', 'Датчики'],
    productCount: 34000,
    featured: false,
    size: 'small',
  },
  {
    id: 'gct',
    name: 'GCT',
    country: 'США',
    flag: '🇺🇸',
    logo: '/brands/gct.png',
    categories: ['Разъёмы', 'USB', 'Клеммы'],
    productCount: 12300,
    featured: false,
    size: 'small',
  },
]
