import { type Category, type Product } from '@/types'

export const categories: Category[] = [
  {
    id: '1',
    slug: 'rezistory',
    name: 'Резисторы',
    icon: '⊖',
    count: 48200,
    description: 'SMD и THT резисторы всех номиналов',
    color: 'from-blue-500/20 to-blue-600/5',
  },
  {
    id: '2',
    slug: 'kondensatory',
    name: 'Конденсаторы',
    icon: '⊣',
    count: 31500,
    description: 'Электролитические, керамические, плёночные',
    color: 'from-cyan-500/20 to-cyan-600/5',
  },
  {
    id: '3',
    slug: 'mikroskhemy',
    name: 'Микросхемы',
    icon: '▣',
    count: 62000,
    description: 'Логика, память, АЦП/ЦАП, усилители',
    color: 'from-indigo-500/20 to-indigo-600/5',
  },
  {
    id: '4',
    slug: 'tranzistory',
    name: 'Транзисторы',
    icon: '◁',
    count: 18700,
    description: 'BJT, MOSFET, IGBT транзисторы',
    color: 'from-violet-500/20 to-violet-600/5',
  },
  {
    id: '5',
    slug: 'rele',
    name: 'Реле',
    icon: '⊏',
    count: 4200,
    description: 'Электромеханические и твердотельные реле',
    color: 'from-emerald-500/20 to-emerald-600/5',
  },
  {
    id: '6',
    slug: 'datchiki',
    name: 'Датчики',
    icon: '◎',
    count: 12800,
    description: 'Температуры, давления, движения, газа',
    color: 'from-teal-500/20 to-teal-600/5',
  },
  {
    id: '7',
    slug: 'kontrollery',
    name: 'Контроллеры',
    icon: '⬛',
    count: 9400,
    description: 'Arduino, STM32, ESP32, Raspberry Pi',
    color: 'from-orange-500/20 to-orange-600/5',
  },
  {
    id: '8',
    slug: 'diody',
    name: 'Диоды',
    icon: '▷',
    count: 22300,
    description: 'Выпрямительные, стабилитроны, Шоттки',
    color: 'from-red-500/20 to-red-600/5',
  },
  {
    id: '9',
    slug: 'svetodiody',
    name: 'Светодиоды',
    icon: '◉',
    count: 8900,
    description: 'SMD, THT, матрицы, RGB, WS2812',
    color: 'from-yellow-500/20 to-yellow-600/5',
  },
  {
    id: '10',
    slug: 'razyomy',
    name: 'Разъёмы',
    icon: '⊞',
    count: 35600,
    description: 'USB, HDMI, штыревые, клеммные колодки',
    color: 'from-pink-500/20 to-pink-600/5',
  },
]

export const products: Product[] = [
  {
    id: '1',
    slug: 'rezistor-smd-0603-10kohm',
    name: 'Резистор SMD 0603 10кОм 1%',
    partNumber: 'RC0603FR-0710KL',
    category: 'Резисторы',
    categorySlug: 'rezistory',
    manufacturer: 'Yageo',
    price: 0.8,
    priceWholesale: 0.35,
    currency: 'RUB',
    inStock: true,
    stockCount: 124500,
    unit: 'шт',
    minOrder: 100,
    description: 'Прецизионный SMD резистор типоразмера 0603 с допуском 1%. Идеален для точных схем измерения.',
    specs: {
      'Типоразмер': '0603 (1608)',
      'Сопротивление': '10 кОм',
      'Допуск': '±1%',
      'Мощность': '0.1 Вт',
      'Рабочее напряжение': '75 В',
      'ТКС': '±100 ppm/°C',
      'Температура': '-55°C … +155°C',
      'Материал': 'Thick Film',
    },
    tags: ['SMD', '0603', 'резистор', 'Yageo', 'прецизионный'],
    featured: true,
  },
  {
    id: '2',
    slug: 'kondensator-keramika-100nf',
    name: 'Конденсатор керамический 100нФ 50В X7R 0805',
    partNumber: 'GRM21BR71H104KA01L',
    category: 'Конденсаторы',
    categorySlug: 'kondensatory',
    manufacturer: 'Murata',
    price: 2.4,
    priceWholesale: 0.9,
    currency: 'RUB',
    inStock: true,
    stockCount: 87200,
    unit: 'шт',
    minOrder: 50,
    description: 'Многослойный керамический конденсатор Murata серии GRM. Стабильная X7R диэлектрическая характеристика.',
    specs: {
      'Типоразмер': '0805 (2012)',
      'Ёмкость': '100 нФ',
      'Допуск': '±10%',
      'Напряжение': '50 В',
      'Диэлектрик': 'X7R',
      'Температура': '-55°C … +125°C',
      'ESR': '< 100 мОм',
    },
    tags: ['SMD', '0805', 'конденсатор', 'Murata', 'X7R', 'блокировочный'],
    featured: true,
  },
  {
    id: '3',
    slug: 'stm32f103c8t6',
    name: 'Микроконтроллер STM32F103C8T6',
    partNumber: 'STM32F103C8T6',
    category: 'Микросхемы',
    categorySlug: 'mikroskhemy',
    manufacturer: 'STMicroelectronics',
    price: 185,
    priceWholesale: 142,
    currency: 'RUB',
    inStock: true,
    stockCount: 2340,
    unit: 'шт',
    minOrder: 1,
    description: 'ARM Cortex-M3 32-битный микроконтроллер 72МГц, 64кБ Flash, 20кБ SRAM. Blue Pill совместимый.',
    specs: {
      'Ядро': 'ARM Cortex-M3',
      'Частота': '72 МГц',
      'Flash': '64 кБ',
      'SRAM': '20 кБ',
      'I/O пины': '37',
      'Интерфейсы': 'SPI, I2C, USART, USB',
      'АЦП': '12-бит, 10 каналов',
      'Корпус': 'LQFP-48',
      'Напряжение': '2.0–3.6 В',
    },
    tags: ['STM32', 'ARM', 'Cortex-M3', 'микроконтроллер', 'LQFP48'],
    featured: true,
  },
  {
    id: '4',
    slug: 'mosfet-irf540n',
    name: 'MOSFET IRF540N N-канальный 100В 33А',
    partNumber: 'IRF540NPBF',
    category: 'Транзисторы',
    categorySlug: 'tranzistory',
    manufacturer: 'Infineon',
    price: 68,
    priceWholesale: 48,
    currency: 'RUB',
    inStock: true,
    stockCount: 8900,
    unit: 'шт',
    minOrder: 1,
    description: 'Мощный N-канальный MOSFET транзистор. Низкое сопротивление открытого канала (44 мОм). TO-220 корпус.',
    specs: {
      'Тип': 'N-channel MOSFET',
      'Uds': '100 В',
      'Id': '33 А',
      'Rds(on)': '44 мОм',
      'Ugs(th)': '2–4 В',
      'Pmax': '130 Вт',
      'Корпус': 'TO-220',
      'Температура': '-55°C … +175°C',
    },
    tags: ['MOSFET', 'N-channel', 'TO-220', 'силовой', 'Infineon'],
    featured: true,
  },
  {
    id: '5',
    slug: 'rele-srd-05vdc-sl-c',
    name: 'Реле электромеханическое SRD-05VDC-SL-C 10А',
    partNumber: 'SRD-05VDC-SL-C',
    category: 'Реле',
    categorySlug: 'rele',
    manufacturer: 'Songle',
    price: 45,
    priceWholesale: 28,
    currency: 'RUB',
    inStock: true,
    stockCount: 5600,
    unit: 'шт',
    minOrder: 1,
    description: 'Миниатюрное электромеханическое реле для управления нагрузкой 220В AC от 5В DC.',
    specs: {
      'Напряжение катушки': '5 В DC',
      'Ток контактов': '10 А',
      'Напряжение контактов': '250 В AC / 30 В DC',
      'Сопротивление катушки': '70 Ом',
      'Ток срабатывания': '≤ 71.4 мА',
      'Ресурс': '100,000 циклов',
      'Корпус': 'SRD-5',
    },
    tags: ['реле', '5В', '220В', 'Arduino', 'автоматика'],
    featured: false,
  },
  {
    id: '6',
    slug: 'esp32-wroom-32',
    name: 'Модуль ESP32-WROOM-32 WiFi+BT',
    partNumber: 'ESP32-WROOM-32',
    category: 'Контроллеры',
    categorySlug: 'kontrollery',
    manufacturer: 'Espressif',
    price: 320,
    priceWholesale: 240,
    currency: 'RUB',
    inStock: true,
    stockCount: 4200,
    unit: 'шт',
    minOrder: 1,
    description: 'Универсальный модуль WiFi + Bluetooth на базе ESP32. 4МБ Flash, 520КБ SRAM. Идеален для IoT.',
    specs: {
      'Процессор': 'Xtensa dual-core LX6 240МГц',
      'Flash': '4 МБ',
      'SRAM': '520 КБ',
      'WiFi': '802.11 b/g/n 2.4ГГц',
      'Bluetooth': 'v4.2 BR/EDR + BLE',
      'GPIO': '34 пина',
      'АЦП': '12-бит, 18 каналов',
      'Питание': '2.7–3.6 В',
    },
    tags: ['ESP32', 'WiFi', 'Bluetooth', 'IoT', 'Espressif'],
    featured: true,
  },
  {
    id: '7',
    slug: 'diod-schottky-ss34',
    name: 'Диод Шоттки SS34 40В 3А SMA',
    partNumber: 'SS34',
    category: 'Диоды',
    categorySlug: 'diody',
    manufacturer: 'Vishay',
    price: 5.5,
    priceWholesale: 2.8,
    currency: 'RUB',
    inStock: true,
    stockCount: 45000,
    unit: 'шт',
    minOrder: 10,
    description: 'Быстродействующий диод Шоттки в корпусе SMA. Малое прямое падение напряжения.',
    specs: {
      'Тип': 'Диод Шоттки',
      'Vr': '40 В',
      'If': '3 А',
      'Vf': '0.45 В при 3А',
      'Trr': '< 10 нс',
      'Корпус': 'SMA (DO-214AC)',
      'Температура': '-65°C … +150°C',
    },
    tags: ['Шоттки', 'SMA', 'диод', 'выпрямитель', 'Vishay'],
    featured: false,
  },
  {
    id: '8',
    slug: 'svetodiod-ws2812b',
    name: 'Светодиод адресный WS2812B RGB SMD5050',
    partNumber: 'WS2812B',
    category: 'Светодиоды',
    categorySlug: 'svetodiody',
    manufacturer: 'WorldSemi',
    price: 18,
    priceWholesale: 8.5,
    currency: 'RUB',
    inStock: true,
    stockCount: 28000,
    unit: 'шт',
    minOrder: 20,
    description: 'Адресный RGB светодиод со встроенным драйвером. 1-Wire протокол управления. Основа NeoPixel лент.',
    specs: {
      'Тип': 'RGB + встроенный IC',
      'Протокол': '1-Wire, 800 кГц',
      'Питание': '3.5–5.3 В',
      'Ток': '≤ 60 мА (все цвета)',
      'Яркость': '16,777,216 цветов',
      'Корпус': 'SMD 5050',
      'Угол': '120°',
    },
    tags: ['WS2812B', 'NeoPixel', 'адресный', 'RGB', 'лента'],
    featured: true,
  },
  {
    id: '9',
    slug: 'lm358-op-amp',
    name: 'ОУ LM358 двойной Rail-to-Rail DIP-8',
    partNumber: 'LM358N',
    category: 'Микросхемы',
    categorySlug: 'mikroskhemy',
    manufacturer: 'Texas Instruments',
    price: 22,
    priceWholesale: 14,
    currency: 'RUB',
    inStock: true,
    stockCount: 18700,
    unit: 'шт',
    minOrder: 1,
    description: 'Популярный двойной операционный усилитель. Одностороннее питание от 3 до 32В. DIP-8 корпус.',
    specs: {
      'Каналы': '2',
      'Питание': '3–32 В (односторонн.)',
      'Полоса пропускания': '1 МГц',
      'Скорость нарастания': '0.3 В/мкс',
      'Ток покоя': '0.7 мА',
      'Входной ток смещения': '20 нА',
      'Корпус': 'DIP-8',
    },
    tags: ['ОУ', 'LM358', 'DIP-8', 'операционный усилитель', 'TI'],
    featured: false,
  },
  {
    id: '10',
    slug: 'razem-usb-type-c',
    name: 'Разъём USB Type-C 2.0 вертикальный SMD',
    partNumber: 'USB4135-GF-A',
    category: 'Разъёмы',
    categorySlug: 'razyomy',
    manufacturer: 'GCT',
    price: 35,
    priceWholesale: 22,
    currency: 'RUB',
    inStock: true,
    stockCount: 12300,
    unit: 'шт',
    minOrder: 5,
    description: 'Высококачественный USB Type-C разъём для поверхностного монтажа. 10000 циклов подключения.',
    specs: {
      'Тип': 'USB Type-C 2.0',
      'Монтаж': 'SMT',
      'Ориентация': 'Вертикальный',
      'Ток': '5 А',
      'Напряжение': '30 В',
      'Ресурс': '10,000 циклов',
      'Корпус': 'SMD',
    },
    tags: ['USB-C', 'разъём', 'SMD', 'Type-C', 'GCT'],
    featured: false,
  },
  {
    id: '11',
    slug: 'optoziscepka-pc817',
    name: 'Оптопара PC817 одноканальная DIP-4',
    partNumber: 'PC817C',
    category: 'Микросхемы',
    categorySlug: 'mikroskhemy',
    manufacturer: 'Sharp',
    price: 14,
    priceWholesale: 7,
    currency: 'RUB',
    inStock: true,
    stockCount: 34000,
    unit: 'шт',
    minOrder: 5,
    description: 'Стандартная одноканальная оптопара для гальванической развязки цепей. Общепромышленный стандарт.',
    specs: {
      'Тип': 'Фототранзистор',
      'CTR': '100–300%',
      'Uiso': '5000 В',
      'If': '1–50 мА',
      'Vce(sat)': '0.1–0.2 В',
      'Частота': '80 кГц',
      'Корпус': 'DIP-4',
    },
    tags: ['оптопара', 'PC817', 'DIP-4', 'развязка', 'Sharp'],
    featured: false,
  },
  {
    id: '12',
    slug: 'datchik-temperatury-ds18b20',
    name: 'Датчик температуры DS18B20 TO-92',
    partNumber: 'DS18B20+',
    category: 'Датчики',
    categorySlug: 'datchiki',
    manufacturer: 'Analog Devices',
    price: 85,
    priceWholesale: 60,
    currency: 'RUB',
    inStock: true,
    stockCount: 6700,
    unit: 'шт',
    minOrder: 1,
    description: 'Цифровой датчик температуры с 1-Wire интерфейсом. Точность ±0.5°C. Без внешних компонентов.',
    specs: {
      'Диапазон': '-55°C … +125°C',
      'Точность': '±0.5°C (от -10 до +85°C)',
      'Разрешение': '9–12 бит (программируемое)',
      'Интерфейс': '1-Wire',
      'Питание': '3.0–5.5 В / паразитный',
      'Время преобразования': '< 750 мс',
      'Корпус': 'TO-92',
    },
    tags: ['DS18B20', 'температура', '1-Wire', 'TO-92', 'Arduino'],
    featured: true,
  },
]

export const featuredProducts = products.filter((p) => p.featured)

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug)
}
